adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # re_path(r'^$', adminapp.index, name='index'),
    re_path(r'^$', adminapp.ShopUserListView.as_view(), name='index'),

    re_path(r'^shopuser/create/$', adminapp.shopuser_create, name='shopuser_create'),
    re_path(r'^shopuser/update/(?P<pk>\d+)/$', adminapp.shopuser_update, name='shopuser_update'),
    re_path(r'^shopuser/delete/(?P<pk>\d+)/$', adminapp.shopuser_delete, name='shopuser_delete'),

    re_path(r'^productcategory/list/$', adminapp.productcategory_list,
            name='productcategory_list'),
    re_path(r'^productcategory/create/$', adminapp.ProductCategoryCreateView.as_view(),
            name='productcategory_create'),
    re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(),
            name='productcategory_update'),
    re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(),
            name='productcategory_delete'),
    re_path(r'^productcategory/products/(?P<pk>\d+)/$', adminapp.productcategory_products,
            name='productcategory_products'),

    re_path(r'^product/create/(?P<pk>\d+)/$', adminapp.product_create,
            name='product_create'),
    re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(),
            name='product_read'),
    re_path(r'^product/update/(?P<pk>\d+)/$', adminapp.product_update,
            name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', adminapp.product_delete,
            name='product_delete'),
]

authapp/urls.py
from django.urls import re_path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.edit, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page  # кеширование для CBV
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),  # ловит пустую строку + переменная для динамического URL

    re_path(r'^category/(?P<pk>\d+)/$', mainapp.category, name='category'),
    re_path(r'^category/(?P<pk>\d+)/ajax/$', cache_page(60)(mainapp.category_ajax)),  # кеширование для CBV

    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^category/(?P<pk>\d+)/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    re_path(r'^category/(?P<pk>\d+)/(?P<page>\d+)/ajax/$', cache_page(60)(mainapp.category_ajax)),

    re_path(r'^hot_deal/$', mainapp.hot_deal, name='hot_deal'),
    re_path(r'^contact/$', mainapp.contact, name='contact'),
]

ordersapp/urls.py
from django.urls import re_path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),

    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),

    # для автообновления цены при добавлении продукта в заказ
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

shop/urls.py
from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings  # чтобы Django раздавал медиафайлы на этапе разработки
from django.conf.urls.static import static  # чтобы Django раздавал медиафайлы на этапе разработки

urlpatterns = [
	re_path(r'^', include('mainapp.urls', namespace='main')),
	re_path(r'^auth/', include('authapp.urls', namespace='auth')),
	re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
	re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
	re_path(r'^order/', include('ordersapp.urls', namespace='order')),

	re_path(r'^', include('social_django.urls', namespace='social')),  # аутентификация через соц сети

	re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:

	import debug_toolbar

	urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	# сообщить Django, что нужно папку на диске ​MEDIA_ROOT ​сделать доступной по сетевому адресу ​MEDIA_URL

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активность', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активность', default=True)

    def __str__(self):
        return self.name + ' (' + self.category.name + ')'

    # Убираем из каталога неактивные продукты
    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('category', 'name')

mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
import json

from .models import ProductCategory, Product
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import never_cache
from django.template.loader import render_to_string
from django.http import JsonResponse


def index(request):
    products = get_products()[:6]  # берем из кешированных продуктов

    context = {
        'page_title': 'главная',
        'products': products,
    }
    return render(request, 'mainapp/index.html', context)


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')
    else:
        return []


def get_same_products(hot_product):
    # Выбираю другие продукты из категории товара hot_product, исключаю из списка hot_product
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


@never_cache
def category(request, pk, page=1):
    pk = int(pk)

    if pk == 0:
        category = {
            'pk': 0,
            'name': 'все'
        }
        products = get_products_ordered_by_price()
    else:
        category = get_category(pk)
        products = get_products_in_category_ordered_by_price(pk)

    paginator = Paginator(products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'products_menu': get_links_meny(),  # берем из кешированного меню
        'category': category,
        'category_products': products_paginator,
        'page_title': 'каталог',
    }
    return render(request, 'mainapp/category_products.html', context)


# @cache_page(3600)
def category_ajax(request, pk, page=1):
    if request.is_ajax():
        pk = int(pk)

        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = get_products_ordered_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_ordered_by_price(pk)

        paginator = Paginator(products, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'products_menu': get_links_meny(),  # берем из кешированного меню
            'category': category,
            'category_products': products_paginator,
            'page_title': 'каталог',
        }

        result = render_to_string(
            'mainapp/includes/inc__products_list_content.html',
            context=context,
            request=request)
        return JsonResponse({'result':result})


def hot_deal(request):
    hot_product = get_hot_product()

    context = {
        'page_title': 'товар',
        'products_menu': get_products_menu(),
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }
    return render(request, 'mainapp/hot_deal.html', context)


def product(request, pk):
    product = get_product(pk)

    context = {
        'page_title': 'страница продукта',
        'products_menu': get_links_meny(),  # берем из кешированного меню
        'category': product.category,
        'object': product,
        'same_products': get_same_products(product),
    }

    return render(request, 'mainapp/product_page.html', context)


def contact(request):
    if settings.LOW_CACHE:
        key = 'locations'
        locations = cache.get(key)
        if locations is None:
            with open('mainapp/json/locations.json', 'r', encoding='utf-8') as f:
                locations = json.load(f)  # dump
            cache.set(key, locations)
    else:
        with open('mainapp/json/locations.json', 'r', encoding='utf-8') as f:
            locations = json.load(f)  # dump

    context = {
        'page_title': 'контакты',
        'locations': locations,
    }

    return render(request, 'mainapp/contact.html', context)


# кеширование меню (memcached)
def get_links_meny():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


# кеширование категорий (memcached)
def get_category(pk):
    if settings.LOW_CACHE:
        key = 'category_' + str(pk)
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


# кеширование продуктов (memcached)
def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


# кеширование продукта (memcached)
def get_product(pk):
    if settings.LOW_CACHE:
        key = 'product_' + pk
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


# кеширование (memcached)
def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


# кеширование (memcached)
def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = 'products_in_category_ordered_by_price_' + str(pk)
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, 
                is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, 
            is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]

mainapp/templates/mainapp/includes/inc__main_menu.html
{% load static %}

<div class="header">
    <a href="{% url 'main:index' %}"><img src="{% static 'images/228.png' %}" alt="logo"></a>
    <ul class="menu">
        <li>
            <a href="{% url 'main:index' %}"
               class="menu__link {% if request.resolver_match.url_name == 'index' %} menu__link_active {% endif %}">
                Главная
            </a>
        </li>
        <li>
            <a href="{% url 'main:category' 0 %}"
               class="menu__link {% if request.resolver_match.url_name == 'interior_product' or request.resolver_match.url_name == 'interior_product_details' or request.resolver_match.url_name == 'category' %} menu__link_active {% endif %}">
                Каталог
            </a>
        </li>
        <li>
            <a href="{% url 'main:contact' %}"
               class="menu__link {% if request.resolver_match.url_name == 'contact' %} menu__link_active {% endif %}">
                Контакты
            </a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <div class="dropdown">
                    <a href="" class="dropdown-toggle menu__link" data-toggle="dropdown">
                        {{ user.first_name|default:'Пользователь' }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'authapp:update' %}" class="menu__link">
                                профиль
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'ordersapp:orders_list' %}" class="menu__link">
                                заказы
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
{#            <li>#}
{#                <div class="dropdown">#}
{#                    <a href="{% url 'authapp:update' %}" class="menu__link">#}
{#                        {{ user.first_name|default:'Пользователь' }}#}
{#                    </a>#}
{#                </div>#}
{#            </li>#}
        {% endif %}
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'adminapp:index' %}" class="menu__link">
                    Администрирование
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'authapp:logout' %}" class="menu__link">
                    выход
                </a>
            {% else %}
                <a href="{% url 'authapp:login' %}" class="menu__link">
                    вход
                </a>
            {% endif %}
        </li>
        <li>
            <a href="#"><img class="menu_search_img" src="{% static 'images/search-solid.svg' %}" alt=""></a>
        </li>
        <li>
            <a href="{% url 'basket:index' %}" style="text-decoration:none;">
                <img class="menu_search_img" src="{% static 'images/shopping-basket-solid.svg' %}" alt="basket">
                {% if basket %}
                    <span class="basket__link">
                    {{ basket.0.total_coast|floatformat:0 }} руб
                    ({{ basket.0.total_quantity }} шт)
                </span>
                {% endif %}
            </a>
        </li>
    </ul>
</div>

mainapp/templates/mainapp/includes/inc__product_menu.html
{% load static %}

<ul class="products_menu">
    <li>
        <a href="{% url 'main:category' 0 %}"
           class="menu__link {% if request.resolver_match.kwargs.pk == '0' %} menu__link_active {% endif %}">
            Все
        </a>
    </li>
    {% for category in products_menu %}
        <li>
            <a href="{% url 'main:category' category.pk %}"
               class="menu__link {% if request.resolver_match.kwargs.pk|add:0 == category.pk %} menu__link_active {% endif %}">
                {{ category.name }}
            </a>
        </li>
    {% endfor %}

</ul>

mainapp/templates/mainapp/includes/inc__products_list_content.html
{% load static %}

    <div class="products  padding_site">

        {% include 'mainapp/includes/inc__product_menu.html' %}

        <div class="product_mini__pictures">
            {% for product in category_products %}
                    <a href="{% url 'main:product' product.pk %}">
                        <img class="mini__pictures_item" src="/media/{{ product.image }}"
                             alt="{{ product.short_desc }}">
                    </a>
            {% endfor %}
        </div>

        <div class="product_mini__refresh">
            {% if category_products.has_previous %}
                <a href="{% url 'main:category_paginator' category.pk category_products.previous_page_number %}"
                   class="paginator">
                   <
                </a>
            {% endif %}
            <span class="paginator_text">
            страница {{ category_products.number }} из {{ category_products.paginator.num_pages }}
            </span>
            {% if category_products.has_next %}
                <a href="{% url 'main:category_paginator' category.pk category_products.next_page_number %}"
                   class="paginator">
                   >
                </a>
            {% endif %}
        </div>
    </div>