adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # re_path(r'^$', adminapp.index, name='index'),
    re_path(r'^$', adminapp.ShopUserListView.as_view(), name='index'),

    re_path(r'^shopuser/create/$', adminapp.shopuser_create, name='shopuser_create'),
    re_path(r'^shopuser/update/(?P<pk>\d+)/$', adminapp.shopuser_update, name='shopuser_update'),
    re_path(r'^shopuser/delete/(?P<pk>\d+)/$', adminapp.shopuser_delete, name='shopuser_delete'),

    re_path(r'^productcategory/list/$', adminapp.productcategory_list,
            name='productcategory_list'),
    re_path(r'^productcategory/create/$', adminapp.ProductCategoryCreateView.as_view(),
            name='productcategory_create'),
    re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(),
            name='productcategory_update'),
    re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(),
            name='productcategory_delete'),
    re_path(r'^productcategory/products/(?P<pk>\d+)/$', adminapp.productcategory_products,
            name='productcategory_products'),

    re_path(r'^product/create/(?P<pk>\d+)/$', adminapp.product_create,
            name='product_create'),
    re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(),
            name='product_read'),
    re_path(r'^product/update/(?P<pk>\d+)/$', adminapp.product_update,
            name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', adminapp.product_delete,
            name='product_delete'),
]

shop/urls.py
from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings  # чтобы Django раздавал медиафайлы на этапе разработки
from django.conf.urls.static import static  # чтобы Django раздавал медиафайлы на этапе разработки

urlpatterns = [
	re_path(r'^', include('mainapp.urls', namespace='main')),
	re_path(r'^auth/', include('authapp.urls', namespace='auth')),
	re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
	re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
	re_path(r'^order/', include('ordersapp.urls', namespace='order')),

	re_path(r'^', include('social_django.urls', namespace='social')),  # аутентификация через соц сети

	re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:

	import debug_toolbar

	urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	# сообщить Django, что нужно папку на диске ​MEDIA_ROOT ​сделать доступной по сетевому адресу ​MEDIA_URL

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.forms import HiddenInput

from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminCreateForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, field in self.fields.item():
                field.widget.attrs['class'] = 'form-control'
                field.help_text = ''

        def clean_age(self):
            data = self.cleaned_data['age']
            if data < 18:
                raise forms.ValidationError('Вы слишком молоды')

            return data


class ShopUserAdminUpdateForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email',
                  'age', 'avatar', 'password', 'is_superuser', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды')

        return data


class ProductCategoryAdminUpdateForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', 
        required=False,  # заполнять не обязательно (для исклчения проблем с валидацией)
        min_value=0, 
        max_value=90,
        initial=0)  # начальное значение

    class Meta:
        model = ProductCategory
        # fields = '__all__'
        exclude = ()  # кортеж с исключенными из отображения полями

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    # def __init__(self, *args, **kwargs):
    #     super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
    #     for field_name, field in self.fields.items():
    #         field.widget.attrs['class'] = 'form-control'
    #         field.help_text = ''


class ProductAdminUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect, request
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminCreateForm, ShopUserAdminUpdateForm, ProductCategoryAdminUpdateForm, \
    ProductAdminUpdateForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product

from django.db import connection
from django.db.models import F


# @user_passes_test (lambda x: x.is_superuser)
# def index(request):
#     object_list = ShopUser.objects.all()
#
#     context = {
#         'page_title': 'администрирование',
#         'object_list': object_list,
#     }
#
#     return render(request, 'adminapp/index.html', context)


class ShopUserListView(ListView):   # CBV
    model = ShopUser
    # template_name = 'adminapp/index.html'

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'администрирование'
        return context


@user_passes_test (lambda x: x.is_superuser)
def shopuser_create(request):
    if request.method == 'POST':
        form = ShopUserAdminCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:index'))
    else:
        form = ShopUserAdminCreateForm()

    content = {
        'title': 'администрирование/новый пользователь',
        'form': form,
    }

    return render(request, 'adminapp/shopuser_update.html', content)


@user_passes_test (lambda x: x.is_superuser)
def shopuser_update(request, pk):
    user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        form = ShopUserAdminUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:index'))
    else:
        form=ShopUserAdminUpdateForm(instance=user)

    content = {
        'title': 'администрирование/редактирование пользователя',
        'form': form,
    }

    return render(request, 'adminapp/shopuser_update.html', content)


@user_passes_test (lambda x: x.is_superuser)
def shopuser_delete(request, pk):
    # get_object_or_404(ShopUser, pk=pk).delete() # удалить навсегда
    user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('myadmin:index'))
    elif request.method == 'GET':
        context = {
            'title': 'администрирование/удаление пользователя',
            'object': user,
        }
        return render(request, 'adminapp/shopuser_delete.html', context)


@user_passes_test (lambda x: x.is_superuser)
def productcategory_list (request):
    object_list = ProductCategory.objects.all()

    context = {
        'title': 'администрирование/категории',
        'object_list': object_list,
    }

    return render(request, 'adminapp/productcategory_list.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_create(request):
#     if request.method == 'POST':
#         form = ProductCategoryAdminUpdateForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     else:
#         form = ProductCategoryAdminUpdateForm()
#
#     context = {
#         'title': 'администрирование/новая категория товара',
#         'form': form
#     }
#
#     return render(request, 'adminapp/productcategory_form.html', context)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    success_url = reverse_lazy('myadmin:productcategory_list')
    # fields = '__all__'
    form_class = ProductCategoryAdminUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/новая категория'
        return context

# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_update(request, pk):
#     productcategory = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         form = ProductCategoryAdminUpdateForm(request.POST, request.FILES, instance=productcategory)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     else:
#         form = ProductCategoryAdminUpdateForm(instance=productcategory)
#
#     context = {
#         'page_title': 'администрирование/редактирование категории товара',
#         'form': form
#     }
#
#     return render(request, 'adminapp/productcategory_form.html', context)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'mainapp/productcategory_form.html'  
    success_url = reverse_lazy('myadmin:productcategory_list')
    form_class = ProductCategoryAdminUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)

        return super().form_valid(form)


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print('db_profile {} for {}:'.format(type, prefix))
    [print(query['sql']) for query in update_queries]


# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_delete(request, pk):
#     productcategory = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         productcategory.is_active = False
#         productcategory.save()
#         return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     elif request.method == 'GET':
#         context = {
#             'title': 'администрировани/удаление категории товара',
#             'object': productcategory
#         }
#
#     return render(request, 'adminapp/productcategory_confirm_delete.html', context)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('myadmin:productcategory_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/удаление'
        return context


@user_passes_test(lambda x: x.is_superuser)
def productcategory_products(request, pk):
    productcategory = get_object_or_404(ProductCategory, pk=pk)
    context = {
        'title': 'администрирование/товары категории',
        'productcategory': productcategory,
        'object_list': productcategory.product_set.all()
    }

    return render(request, 'adminapp/product_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_create(request, pk):
    productcategory = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:productcategory_products',
                                                kwargs={'pk': pk}))
    else:
        form = ProductAdminUpdateForm(initial={'category': productcategory})

    content = {
        'title': 'администрирование/новый товар',
        'form': form
    }

    return render(request, 'adminapp/product_update.html', content)


@user_passes_test((lambda x: x.is_superuser))
def product_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:productcategory_products',
                                                kwargs={'pk': product.category.pk}))
    else:
        form = ProductAdminUpdateForm(instance=product)

    content = {
        'title': 'администрирование/редактирование товара',
        'form': form,
        'object': product
    }

    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda x: x.is_superuser)
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('myadmin:productcategory_products',
                                            kwargs={'pk': product.category.pk}))
    elif request.method == 'GET':
        context = {
            'title': 'администрировние/удаление товара',
            'object': product
        }

    return render(request, 'adminapp/product_delete.html', context)


# @user_passes_test(lambda x: x.is_superuser)
# def product_read(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     context = {
#         'title': 'администрировани/товар подробно',
#         'object': product
#     }
#
#     return render(request, 'adminapp/product_detail.html', context)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style_admin.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/montserrat/montserrat.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Панель администратора
    </div>
    {% block menu %}
        <div class="admin_menu">
            <ul class="menu">
                <li>
                    <a href="{% url 'main:index' %}">на сайт</a>
                </li>
                <li>
                    <a href="{% url 'myadmin:index' %}"
                       class="{% if request.resolver_match.url_name == 'index' %} active {% endif %}">
                        пользователи
                    </a>
                </li>
                <li>
                    <a href="{% url 'myadmin:productcategory_list' %}"
                    class="{% if request.resolver_match.url_name == 'productcategory_list' or productcategory.name %}active{% endif %}">
                    категории{% if productcategory %}: <span>{{ productcategory.name }}</span>{% endif %}
                    </a>
                </li>
            </ul>
        </div>
    {% endblock %}

    {% block container %}
    {% endblock %}

</div>
</body>
</html>

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить продукт <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'myadmin:productcategory_products' object.category.pk %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="categories_list">
        <a href="{% url 'myadmin:product_create' productcategory.pk %}"
           class="btn btn-primary new_category">
            новый продукт
        </a>
    </div>
    <div class="categories_list">
        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="/media/{{ object.image|default:'products_image/default.jpg' }}" alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <a href="{% url 'myadmin:product_read' object.pk %}"
                       class="btn btn-info">
                        подробнее
                    </a>
                    <a href="{% url 'myadmin:product_update' object.pk %}"
                       class="btn btn-success">
                        редактировать
                    </a>
                    <a href="{% url 'myadmin:product_delete' object.pk %}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
            </div>
            <div class="summary">
                <b>цена</b>
                <p>{{ object.price }} руб</p>
                <b>количество</b>
                <p>{{ object.quantity }}</p>
            </div>
            <div class="product_desc">
                {{ object.description }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
{#        <a href="{% url 'myadmin:productcategory_products' object.category.pk %}"#}
{#           class="btn btn-primary form-control last">#}
{#            к списку продуктов#}
{#        </a>#}
        <a href="{% url 'myadmin:productcategory_products' request.resolver_match.kwargs.pk %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

adminapp/templates/adminapp/productcategory_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="categories_list">
        <a href="{% url 'myadmin:productcategory_create' %}"
           class="btn btn-primary new_category">
            новая категория
        </a>
        {% for object in object_list %}
            <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <a href="{% url 'myadmin:productcategory_products' object.pk %}"
                       class="btn btn-info">
                        товары категории
                    </a>
                    <a href="{% url 'myadmin:productcategory_update' object.pk %}"
                       class="btn btn-success">
                        редактировать
                    </a>
                    <a href="{% url 'myadmin:productcategory_delete' object.pk %}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="category_desc">
                    {{ object.description }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/shopuser_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ object.username }}
        {% if object.first_name %}
        ({{ object.first_name|title }}
        {% if object.last_name %}
            {{ object.last_name|title }}
        {% endif %})
        {% endif %}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'myadmin:index' %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

adminapp/templates/adminapp/shopuser_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a href="{% url 'myadmin:index' %}"
       class="btn btn-primary form-control last">
        к списку пользователей
    </a>

{% endblock %}