basketapp/urls.py
from django.urls import path, re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', basketapp.index, name='index'),
    re_path('add/(?P<pk>\d+)/', basketapp.basket_add, name='add'),
    re_path('delete/(?P<pk>\d+)/', basketapp.basket_delete, name='delete'),
    re_path('update/(?P<pk>\d+)/(?P<quantity>\d+)/', basketapp.basket_update, name='update'),
]

mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page  # кеширование для CBV
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),  # ловит пустую строку + переменная для динамического URL

    re_path(r'^category/(?P<pk>\d+)/$', mainapp.category, name='category'),
    re_path(r'^category/(?P<pk>\d+)/ajax/$', cache_page(60)(mainapp.category_ajax)),  # кеширование для CBV

    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^category/(?P<pk>\d+)/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    re_path(r'^category/(?P<pk>\d+)/(?P<page>\d+)/ajax/$', cache_page(60)(mainapp.category_ajax)),

    re_path(r'^hot_deal/$', mainapp.hot_deal, name='hot_deal'),
    re_path(r'^contact/$', mainapp.contact, name='contact'),
]

shop/urls.py
from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings  # чтобы Django раздавал медиафайлы на этапе разработки
from django.conf.urls.static import static  # чтобы Django раздавал медиафайлы на этапе разработки

urlpatterns = [
	re_path(r'^', include('mainapp.urls', namespace='main')),
	re_path(r'^auth/', include('authapp.urls', namespace='auth')),
	re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
	re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
	re_path(r'^order/', include('ordersapp.urls', namespace='order')),

	re_path(r'^', include('social_django.urls', namespace='social')),  # аутентификация через соц сети

	re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:

	import debug_toolbar

	urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	# сообщить Django, что нужно папку на диске ​MEDIA_ROOT ​сделать доступной по сетевому адресу ​MEDIA_URL

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активность', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активность', default=True)

    def __str__(self):
        return self.name + ' (' + self.category.name + ')'

    # Убираем из каталога неактивные продукты
    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('category', 'name')

mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
import json

from .models import ProductCategory, Product
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import never_cache
from django.template.loader import render_to_string
from django.http import JsonResponse


def index(request):
    products = get_products()[:6]  # берем из кешированных продуктов

    context = {
        'page_title': 'главная',
        'products': products,
    }
    return render(request, 'mainapp/index.html', context)


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')
    else:
        return []


def get_same_products(hot_product):
    # Выбираю другие продукты из категории товара hot_product, исключаю из списка hot_product
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


@never_cache
def category(request, pk, page=1):
    pk = int(pk)

    if pk == 0:
        category = {
            'pk': 0,
            'name': 'все'
        }
        products = get_products_ordered_by_price()
    else:
        category = get_category(pk)
        products = get_products_in_category_ordered_by_price(pk)

    paginator = Paginator(products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'products_menu': get_links_meny(),  # берем из кешированного меню
        'category': category,
        'category_products': products_paginator,
        'page_title': 'каталог',
    }
    return render(request, 'mainapp/category_products.html', context)


# @cache_page(3600)
def category_ajax(request, pk, page=1):
    if request.is_ajax():
        pk = int(pk)

        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = get_products_ordered_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_ordered_by_price(pk)

        paginator = Paginator(products, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'products_menu': get_links_meny(),  # берем из кешированного меню
            'category': category,
            'category_products': products_paginator,
            'page_title': 'каталог',
        }

        result = render_to_string(
            'mainapp/includes/inc__products_list_content.html',
            context=context,
            request=request)
        return JsonResponse({'result':result})


def hot_deal(request):
    hot_product = get_hot_product()

    context = {
        'page_title': 'товар',
        'products_menu': get_products_menu(),
        'hot_product': hot_product,
        'same_products': get_same_products(hot_product),
    }
    return render(request, 'mainapp/hot_deal.html', context)


def product(request, pk):
    product = get_product(pk)

    context = {
        'page_title': 'страница продукта',
        'products_menu': get_links_meny(),  # берем из кешированного меню
        'category': product.category,
        'object': product,
        'same_products': get_same_products(product),
    }

    return render(request, 'mainapp/product_page.html', context)


def contact(request):
    if settings.LOW_CACHE:
        key = 'locations'
        locations = cache.get(key)
        if locations is None:
            with open('mainapp/json/locations.json', 'r', encoding='utf-8') as f:
                locations = json.load(f)  # dump
            cache.set(key, locations)
    else:
        with open('mainapp/json/locations.json', 'r', encoding='utf-8') as f:
            locations = json.load(f)  # dump

    context = {
        'page_title': 'контакты',
        'locations': locations,
    }

    return render(request, 'mainapp/contact.html', context)


# кеширование меню (memcached)
def get_links_meny():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


# кеширование категорий (memcached)
def get_category(pk):
    if settings.LOW_CACHE:
        key = 'category_' + str(pk)
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


# кеширование продуктов (memcached)
def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


# кеширование продукта (memcached)
def get_product(pk):
    if settings.LOW_CACHE:
        key = 'product_' + pk
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


# кеширование (memcached)
def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


# кеширование (memcached)
def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = 'products_in_category_ordered_by_price_' + str(pk)
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, 
                is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, 
            is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|title }}</title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/montserrat/montserrat.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {# <script src="{% static 'js/main_scripts.js' %}"></script> #}
    {% endblock %}
</head>



<body>
<div class="my_container">
    {% block container %}
    {% endblock %}
    <div class="footer padding_site">
        <div class="footer__text_block">
            <div class="footer__block">
                <div class="footer__block_contact">
                    <p class="footer__tittle">Свяжитесь с нами</p>
                    <p class="footer_text">Москва, ул. Тверская, 2а</p>
                    <p class="footer_text">Тел. +7 495 755 55 45</p>
                    <a href="" class="footer_text_mail">info@ringbox.com</a>
                </div>
                <div class="footer__block_info">
                    <p class="footer__tittle">Полезная информация</p>
                    <div class="footer__hyperlink_container">
                        <div class="footer__hyperlink">
                            <a href="#" class="footer_text_bold">Условия продажи</a>
                            <a href="#" class="footer_text_bold">Доставка</a>
                        </div>
                        <div class="footer__hyperlink2">
                            <a href="#" class="footer_text_bold">Карьера</a>
                            <a href="#" class="footer_text_bold">Обмен и возврат</a>
                        </div>
                    </div>
                </div>
                <div class="footer__block_mailing">
                    <p class="footer__tittle">Давайте оставаться на связи!</p>
                    <p class="footer_text">Подпишитесь, чтобы узнать о наших последних новостях, продуктах и ​​специальных предложениях только для подписчиков.</p>
                    <form class="form_plane" action="#">
                        <input class="entry_field" type="text" placeholder="your email address">
                        <button class="button_plane"><img class="plane_button"
                                                          src="{% static 'images/paper-plane-solid.svg' %}" alt="">
                        </button>
                    </form>
                </div>
            </div>
            <div class="footer__footer">
                <p class="footer__footer_copy">© Copyright - LOVELY RING BOX {% now 'Y' %}. Все права защищены.</p>
                <div>
                    <a class="footer__footer_link" href="#"><img src="{% static 'images/social-links_facebook.png' %}"
                                                                 alt="facebook"></a>
                    <a class="footer__footer_link" href="#"><img src="{% static 'images/social-links_twit.png' %}"
                                                                 alt="twitter"></a>
                    <a class="footer__footer_link" href="#"><img src="{% static 'images/social-links_google.png' %}"
                                                                 alt="google+"></a>
                    <a class="footer__footer_link" href="#"><img src="{% static 'images/social-links_pint.png' %}"
                                                                 alt="pinterest"></a>
                </div>
                <p class="footer__footer_copy">Terms & Conditions / Privacy policy & Cookies</p>
            </div>
        </div>
    </div>
</div>
</body>

</html>

mainapp/templates/mainapp/category_products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}

	<div class="contact_padding padding_site">

        {% include 'mainapp/includes/inc__main_menu.html' %}

        <div class="product_slider__text">
            <h2 class="slider__h2_product_sort">{{ category.name|title }}</h2>
        </div>
    </div>

    <div class='details'>
        {% include 'mainapp/includes/inc__products_list_content.html' %}
    </div>

    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="contact_padding padding_site">

        {% include 'mainapp/includes/inc__main_menu.html' %}

    </div>
    <div class="slider__text">
        <h2 class="slider__h2_v2">Contact Us</h2>
    </div>

    <div class="adress padding_site">
        {% for item in locations %}
            <div class="adress_block">
                <div class="adress_bloch_point"><img src="{% static 'images/point.png' %}" alt=""></div>
                <h3 class="adress_bloch_h3">{{ item.city }}</h3>
                <div class="adress_bloch_text">
                    <div class="adress_block_text_format">
                        <p class="adress_block_text_color">Phone:</p>
                        {{ item.phone }}
                    </div>
                    <div class="adress_block_text_format">
                        <p class="adress_block_text_color">Email:</p>
                        <a class="adress_block_mail" href="#">{{ item.email }}</a>
                    </div>
                    <div class="adress_block_text_format">
                        <p class="adress_block_text_color">Address:</p>
                        <p class="adress_block_text_weighr">{{ item.address }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/hot_deal.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="interior_product_header padding_site">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="interior_product_menu padding_site">

        {% include 'mainapp/includes/inc__product_menu.html' %}

    </div>

    <div class="product padding_site">
        <div class="product_fotos">
            <div>
                <img class="product_fotos_big" src="/media/{{ hot_product.image }}" alt="{{ hot_product.short_desc }}">
            </div>
            <div class="product_fotos_small">
                <a href="#">
                    <img class="fotos_small" src="/media/{{ hot_product.image }}" alt="{{ hot_product.short_desc }}">
                </a>
                <a href="#">
                    <img class="fotos_small" src="/media/{{ hot_product.image }}" alt="{{ hot_product.short_desc }}">
                </a>
            </div>
        </div>
        <div class="product_text">
            <div class="product_text__title">
                <h2 class="product_text__h2">{{ hot_product.name }}</h2>
                <p class="product_text__p">Акция</p>
                <div class="product_text_price_hot">{{ hot_product.price|floatformat:0 }}<span
                        class="little_text"> руб.</span></div>
            </div>
            <a href="{% url 'basket:add' hot_product.pk %}" class="buttom_product_details">Добавить в корзину<img
                    class="arrow_white" src="{% static 'images/arrow_31.png' %}" alt="arrow"></a>
            <div class="product_text__description">
                <p class="product_text_info">{{ hot_product.short_desc }}</p>
                <p class="product_text_info">{{ hot_product.description }}</p>

            </div>
        </div>
    </div>

    <div class="related_product padding_site">
        <div class="mini__picture_menu">
            <p class="mibi__pecture_text">Похожие товары</p>
            <a href="{% url 'main:category' 0 %}" class="shop__product_explore"> посмотреть все <img
                    src="{% static 'images/arrow.png' %}" alt="arrow"></a>
        </div>


        <div class="mini__pictures_pictures">
            {% for product in same_products %}
                <a href="{% url 'main:product' product.pk %}">
                    <img class="mini__pictures_item" src="/media/{{ product.image }}" alt="{{ product.name }}">
                </a>
            {% endfor %}
        </div>


    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="slider padding_site">

        {% include 'mainapp/includes/inc__main_menu.html' %}

        <div class="slider__text">
            <p class="slider__text_top">TRENDING</p>
            <h2 class="slider__h2">Ring box</h2>
            <p class="slider__text_info">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <a href="{% url 'main:category' 0 %}" class="button">В магазин<img class="arrow"
                                                                               src="{% static 'images/arrow.png' %}"
                                                                               alt="arrow"></a>
        </div>
        <div class="slider__paginatiom">
            <a href="" class="slider__circle"></a>
            <a href="" class="slider__circle slider__circle_active"></a>
            <a href="" class="slider__circle"></a>
        </div>
    </div>

    <div class="shop__product padding_site">
        <div class="shop__product_menu">
            <ul class="shop__menu">
                <li><a href="#" class="shop__menulink shop__menulink_active">Featured</a></li>
                <li><a href="#" class="shop__menulink">New</a></li>
            </ul>
            <a href="{% url 'main:category' 0 %}" class="shop__product_explore">посмотреть все <img
                    src="{% static 'images/arrow.png' %}" alt="arrow"></a>
        </div>
        <div class="shop__product_image">
            <div class="product__content" style="background-image: url({% static 'images/product-1_172.jpg' %})">
                <div class="product__box">
                    <div class="product__content_image">
                        <a href="#"><img class="button__arrow" src="{% static 'images/arrow.png' %}" alt="arrow"></a>
                        <h3 class="shop__product_header">Ring box</h3>
                        <p class="shop__product_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </div>
                </div>
            </div>
            <div class="product__content" style="background-image: url({% static 'images/product-2.jpg' %})">
                <div class="product__box">
                    <div class="product__content_image">
                        <a href="#"><img class="button__arrow" src="{% static 'images/arrow.png' %}" alt="arrow"></a>
                        <h3 class="shop__product_header">Ring box</h3>
                        <p class="shop__product_p">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                </div>
            </div>
            <div class="product__content" style="background-image: url({% static 'images/product-3.jpg' %})">
                <div class="product__box">
                    <div class="product__content_image">
                        <a href="#"><img class="button__arrow" src="{% static 'images/arrow.png' %}" alt="arrow"></a>
                        <h3 class="shop__product_header">Ring box</h3>
                        <p class="shop__product_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua.</p>
                    </div>
                </div>
            </div>
            <div class="product__content" style="background-image: url({% static 'images/product-4.jpg' %})">
                <div class="product__box">
                    <div class="product__content_image">
                        <a href="#"><img class="button__arrow" src="{% static 'images/arrow.png' %}" alt="arrow"></a>
                        <h3 class="shop__product_header">Ring box</h3>
                        <p class="shop__product_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="two__product">
        <div class="product__one">
            <div class="two__product_text">
                <p class="product__text_top">exclusive</p>
                <h2 class="product__h2">Ring Box</h2>
                <p class="product__text_info">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                <a href="{% url 'main:category' 0 %}" class="button">В магазин<img class="arrow"
                                                                                   src="{% static 'images/arrow.png' %}"
                                                                                   alt="arrow"></a>
            </div>
        </div>
        <div class="product__two">
            <div class="two__product_text">
                <p class="product__text_top">exclusive</p>
                <h2 class="product__h2">Ring box</h2>
                <p class="product__text_info">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua.</p>
                <a href="{% url 'main:category' 0 %}" class="button">В магазин<img class="arrow"
                                                                                   src="{% static 'images/arrow.png' %}"
                                                                                   alt="arrow"></a>
            </div>
        </div>
    </div>

    <div class="mini__picture padding_site">
        <div class="mini__picture_menu">
            <p class="mibi__pecture_text">Trending Products</p>
            <a href="{% url 'main:category' 0 %}" class="shop__product_explore"> посмотреть все <img
                    src="{% static 'images/arrow.png' %}" alt="arrow"></a>
        </div>
        <div class="mini__pictures_pictures">
            {% for product in products %}
            <a href="{% url 'main:product' product.pk %}">
                <img class="mini__pictures_item" src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
            </a>
            {% endfor %}
        </div>
    </div>

    {# <div class="slider__two padding_site"> #}
        {# <div class="slider__text"> #}
            {# <p class="slider__two_text_top">Hot deal</p> #}
            {# <h2 class="slider__h2">Fishnet Chair</h2> #}
            {# <p class="slider__text_info">Seat and back with upholstery made of cold cure foam. Steel frame, available in #}
                {# matt powder-coated black</p> #}
            {# <a href="{% url 'main:category' 0 %}" class="button">В магазин<img class="arrow" #}
                                                                               {# src="{% static 'images/arrow.png' %}" #}
                                                                               {# alt="arrow"></a> #}
        {# </div> #}
        {# <div class="slider__paginatiom"> #}
            {# <a href="" class="slider__circle"></a> #}
            {# <a href="" class="slider__circle slider__circle_active"></a> #}
            {# <a href="" class="slider__circle"></a> #}
        {# </div> #}
    {# </div> #}

    {# <div class="five__picture padding_site"> #}
        {# <div class="five__picture_one"> #}
            {# <div class="slider__lext_little"> #}
                {# <p class="product__text_top">exclusive</p> #}
                {# <h2 class="product__h2">Fishnet Chair</h2> #}
                {# <p class="product__text_info">Seat and back with upholstery made of cold cure foam. Steel frame, #}
                    {# available in matt</p> #}
                {# <a href="{% url 'main:category' 0 %}" class="button">В магазин<img class="arrow" #}
                                                                                   {# src="{% static 'images/arrow.png' %}" #}
                                                                                   {# alt="arrow"></a> #}
            {# </div> #}
        {# </div> #}
        {# <div class="five__picture_four"> #}
            {# <div class="five__picture_pictures"><img src="{% static 'images/product-2-sm.jpg' %}" alt="lamp"></div> #}
            {# <div class="five__picture_pictures"><img src="{% static 'images/product-3-sm.jpg' %}" alt="sofa"></div> #}
            {# <div class="five__picture_pictures"><img src="{% static 'images/product-4-sm.jpg' %}" alt="clock"></div> #}
            {# <div class="five__picture_pictures"><img src="{% static 'images/product-5-sm.jpg' %}" alt="lamp"></div> #}
        {# </div> #}
    {# </div> #}

    {# <div class="box__follow padding_site"> #}
        {# <div class="follow__text"> #}
            {# <p class="slider__text_mobile">mobile app</p> #}
            {# <h2 class="slider__h2">Find. Follow. Favorite.</h2> #}
            {# <p class="slider__text_mobile_info">Save your favorites and share your style.</p> #}
            {# <div class="mobile__store"> #}
                {# <a class="mobile__store_link" href="#"><img src="{% static 'images/app-store.jpg' %}" #}
                                                            {# alt="app_store"></a> #}
                {# <a class="mobile__store_link" href="#"><img src="{% static 'images/google-play.jpg' %}" #}
                                                            {# alt="google_play"></a> #}
            {# </div> #}
        {# </div> #}
    {# </div> #}
{% endblock %}

mainapp/templates/mainapp/product_page.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="interior_product_header padding_site">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="interior_product_menu padding_site">

        {% include 'mainapp/includes/inc__product_menu.html' %}

    </div>

    <div class="product padding_site">
        <div class="product_fotos">
            <div>
                <img class="product_fotos_big" src="/media/{{ object.image }}" alt="{{ object.short_desc }}">
            </div>
            <div class="product_fotos_small">
                <a href="#">
                    <img class="fotos_small" src="/media/{{ object.image }}" alt="{{ object.short_desc }}">
                </a>
                <a href="#">
                    <img class="fotos_small" src="/media/{{ object.image }}" alt="{{ object.short_desc }}">
                </a>
            </div>
        </div>
        <div class="product_text">
            <div class="product_text__title">
                <h2 class="product_text__h2">{{ object.name }}</h2>
                <div class="product_text_price">{{ object.price|floatformat:0 }}<span class="little_text"> руб.</span>
                </div>
            </div>
            <a href="{% url 'basket:add' object.pk %}" class="buttom_product_details">Добавить в корзину<img
                    class="arrow_white" src="{% static 'images/arrow_31.png' %}" alt="arrow"></a>
            <div class="product_text__description">
                <p class="product_text_info">Остаток на складе: {{ object.quantity }}</p>
                <p class="product_text_info">{{ object.short_desc }}</p>
                <p class="product_text_info">{{ object.description }}</p>

            </div>
        </div>
    </div>

    <div class="related_product padding_site">
        <div class="mini__picture_menu">
            <p class="mibi__pecture_text">Похожие товары</p>
            <a href="{% url 'main:category' 0 %}" class="shop__product_explore"> посмотреть все <img
                    src="{% static 'images/arrow.png' %}" alt="arrow"></a>
        </div>


        <div class="mini__pictures_pictures">
            {% for product in same_products %}
                <a href="#">
                    <img class="mini__pictures_item" src="/media/{{ product.image }}" alt="{{ product.name }}">
                </a>
            {% endfor %}
        </div>


    </div>
{% endblock %}