mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page  # кеширование для CBV
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),  # ловит пустую строку + переменная для динамического URL

    re_path(r'^category/(?P<pk>\d+)/$', mainapp.category, name='category'),
    re_path(r'^category/(?P<pk>\d+)/ajax/$', cache_page(60)(mainapp.category_ajax)),  # кеширование для CBV

    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^category/(?P<pk>\d+)/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    re_path(r'^category/(?P<pk>\d+)/(?P<page>\d+)/ajax/$', cache_page(60)(mainapp.category_ajax)),

    re_path(r'^hot_deal/$', mainapp.hot_deal, name='hot_deal'),
    re_path(r'^contact/$', mainapp.contact, name='contact'),
]

ordersapp/urls.py
from django.urls import re_path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),

    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),

    # для автообновления цены при добавлении продукта в заказ
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

shop/urls.py
from django.contrib import admin
from django.urls import include, re_path
from django.conf import settings  # чтобы Django раздавал медиафайлы на этапе разработки
from django.conf.urls.static import static  # чтобы Django раздавал медиафайлы на этапе разработки

urlpatterns = [
	re_path(r'^', include('mainapp.urls', namespace='main')),
	re_path(r'^auth/', include('authapp.urls', namespace='auth')),
	re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
	re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
	re_path(r'^order/', include('ordersapp.urls', namespace='order')),

	re_path(r'^', include('social_django.urls', namespace='social')),  # аутентификация через соц сети

	re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:

	import debug_toolbar

	urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	# сообщить Django, что нужно папку на диске ​MEDIA_ROOT ​сделать доступной по сетевому адресу ​MEDIA_URL

ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в работу'),
        (PROCEEDED, 'обрабатывается'),
        (PAID, 'оплачен'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True, db_index=True)

    class Meta:
        ordering = ('-created',)  # сортировка в обратном порядке
        verbose_name = 'заказ'  # имя класса в единственном числе
        verbose_name_plural = 'заказы'  # имя класса во множественном числе

    def __str__(self):
        return 'Текущий заказ: ' + self.id

    # объединение get_total_quantity и get_total_cost для кеширования через with
    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }


    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    # переопределяем метод удаляющий объект
    def delete(self):
        for item in self.orderitems.select_related():
            # корректируем остатки продуктов на складе
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='orderitems',  # дает доступ к элементам заказа через атрибут 'orderitems'
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)
    # переменная для изменения продуктов на складе (2 метод изменения кол-ва на складе)
    # objects = OrderItemQuerySet.as_manager()

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

ordersapp/forms.py
from django import forms

from mainapp.models import Product, ProductCategory
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)  # поля, которые необходимо исключить из формы

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)  # для вывода цены товара в форму

    class Meta:
        model = OrderItem
        exclude = ()  # поля, которые необходимо исключить из формы
        # поле не должно сохраняться в базу и проходить валидацию - задаем аргумент «required=False​»

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['product'].queryset = Product.get_items().select_related()  # Убираем из каталога неактивные продукты

ordersapp/views.py
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction
from django.db.models import F

from django.forms import inlineformset_factory

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


class OrderList(ListView):
	model = Order

	def get_queryset(self):  # переопределение метода, чтобы пользователь видел только свои заказы
		return Order.objects.filter(user=self.request.user)

	@method_decorator(login_required())
	def dispatch(self, *args, **kwargs):
		return super(ListView, self).dispatch(*args, **kwargs)


class OrderItemsCreate(CreateView):
	model = Order
	fields = []  # Список полей пустой, так как в соответствии с моделью все они, кроме пользователя «user»,
	# создаются автоматически.
	success_url = reverse_lazy('ordersapp:orders_list')

	def get_context_data(self, **kwargs):
		# получаем текущий контекст
		data = super(OrderItemsCreate, self).get_context_data(**kwargs)
		OrderFormSet = inlineformset_factory(Order,
											 OrderItem,
											 form=OrderItemForm,
											 extra=1)  # пустая форма для добавления продуктов в заказ

		# После того, как пользователь нажмет на форме кнопку «Сохранить», создаем набор форм заново на основе данных
		# формы, переданных методом POST
		if self.request.POST:
			formset = OrderFormSet(self.request.POST)
		else:
			basket_items = Basket.get_items(self.request.user)
			# если корзина не пустая
			if len(basket_items):
				# обеспечиваем создание элементов заказа одновременно с самим заказом
				OrderFormSet = inlineformset_factory(Order,  # родительский класс
													 OrderItem,
													 # класс, на основе которого будет создаваться набор форм класса,
													 # указанного в именованном аргументе «form=OrderItemForm»
													 form=OrderItemForm,
													 # создаем набор в котором число форм = числу объектов в корзине
													 extra=len(basket_items))
				formset = OrderFormSet()
				# Заполняем в каждой форме поля «product» и «quantity». Чистим корзину.
				for num, form in enumerate(formset.forms):
					form.initial['product'] = basket_items[num].product
					form.initial['quantity'] = basket_items[num].quantity
					form.initial['price'] = basket_items[num].product.price
				basket_items.delete()
			else:
				# Если корзина пустая - создаем набор с одной чистой формой.
				formset = OrderFormSet()

		# добавляем данные в контекст
		data['orderitems'] = formset
		return data

	# валидация формы
	def form_valid(self, form):
		# получаем набор форм из контекста
		context = self.get_context_data()
		orderitems = context['orderitems']

		# Сохранение заказа и его элементов лучше выполнять как атомарную операцию - если произойдет сбой,
		# вообще никакие данные не сохранятся. Воспользуемся для этого методом «atomic()» модуля
		# «django.db.transaction»
		with transaction.atomic():
			# Чтобы форма создания самого заказа прошла валидацию перед сохранением, необходимо задать обязательный
			# для модели класса «Order»  атрибут «user»
			form.instance.user = self.request.user
			self.object = form.save()
			if orderitems.is_valid():
				orderitems.instance = self.object
				orderitems.save()

		# удаляем пустой заказ
		get_sum = self.object.get_summary()
		if get_sum.get('total_cost') == 0:
			self.object.delete()

		return super(OrderItemsCreate, self).form_valid(form)

	@method_decorator(login_required())
	def dispatch(self, *args, **kwargs):
		return super(CreateView, self).dispatch(*args, **kwargs)


class OrderItemsUpdate(UpdateView):
	model = Order
	fields = []  # Список полей пустой, так как в соответствии с моделью все они, кроме пользователя «user»,
	# создаются автоматически.
	success_url = reverse_lazy('ordersapp:orders_list')

	def get_context_data(self, **kwargs):
		# получаем текущий контекст
		data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
		OrderFormSet = inlineformset_factory(Order,
											 OrderItem,
											 form=OrderItemForm,
											 extra=1)  # пустая форма для добавления продуктов в заказ

		# После того, как пользователь нажмет на форме кнопку «Сохранить», создаем набор форм заново на основе данных
		# формы, переданных методом POST
		if self.request.POST:
			data['orderitems'] = OrderFormSet(self.request.POST,
											  instance=self.object)
		else:
			# для вывода цены в форме
			queryset = self.object.orderitems.select_related()  # оптимизация запроса
			formset = OrderFormSet(instance=self.object, queryset=queryset)
			for form in formset.forms:
				if form.instance.pk:
					form.initial['price'] = form.instance.product.price
			data['orderitems'] = formset
		return data

	# валидация формы
	def form_valid(self, form):
		# получаем набор форм из контекста
		context = self.get_context_data()
		orderitems = context['orderitems']

		# Сохранение заказа и его элементов лучше выполнять как атомарную операцию - если произойдет сбой,
		# вообще никакие данные не сохранятся. Воспользуемся для этого методом «atomic()» модуля
		# «django.db.transaction»
		with transaction.atomic():
			# Чтобы форма создания самого заказа прошла валидацию перед сохранением, необходимо задать обязательный
			# для модели класса «Order»  атрибут «user»
			self.object = form.save()
			if orderitems.is_valid():
				orderitems.instance = self.object
				orderitems.save()

		# удаляем пустой заказ
		get_sum = self.object.get_summary()
		if get_sum.get('total_cost') == 0:
			self.object.delete()

		return super(OrderItemsUpdate, self).form_valid(form)

	@method_decorator(login_required())
	def dispatch(self, *args, **kwargs):
		return super(UpdateView, self).dispatch(*args, **kwargs)


class OrderRead(DetailView):
	model = Order

	def get_context_data(self, **kwargs):
		context = super(OrderRead, self).get_context_data(**kwargs)
		context['title'] = 'заказ/просмотр'
		return context

	@method_decorator(login_required())
	def dispatch(self, *args, **kwargs):
		return super(DetailView, self).dispatch(*args, **kwargs)


class OrderDelete(DeleteView):
	model = Order
	success_url = reverse_lazy('ordersapp:orders_list')


def order_forming_complete(request, pk):
	order = get_object_or_404(Order, pk=pk)
	# После перехода пользователя по ссылке ​«​совершить покупку​»​ будет установлен статус заказа:
	order.status = Order.SENT_TO_PROCEED
	order.save()
	return HttpResponseRedirect(reverse('ordersapp:orders_list'))


# обновление кол-ва товаров на складе
# «sender»​ - класс отправителя
# «update_fields»​ - имена обновляемых полей
# «instance»​ - сам обновляемый объек
@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, raw, **kwargs):
	if update_fields is 'quantity' or 'product' and not raw:
		# Проверяем, новый это объект или уже существующий
		if instance.pk:
			instance.product.quantity = F('quantity') - (instance.quantity - sender.get_item(instance.pk).quantity)
			# instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
		else:
			instance.product.quantity = F('quantity') - instance.quantity
			# instance.product.quantity -= instance.quantity
		instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
	instance.product.quantity = F('quantity') + instance.quantity
	instance.product.save()


# для автообновления цены при добавлении продукта в заказ
def get_product_price(request, pk):
	if request.is_ajax():
		product = Product.objects.filter(pk=int(pk)).first()
		if product:
			return JsonResponse({'price': product.price})
		else:
			return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style_admin.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/jquery.formset.js' %}"> </script>
        <script src="{% static 'js/orders_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="order_container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete">
        <div class="h1">
            Уверены, что хотите удалить?
        </div>
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
        </button>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends 'ordersapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}

    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <img src="{{ item.product.image|media_folder_products }}"
                     alt="{{ item.product.short_desc }}">
                <span class="category_name">
            {{ item.product.category.name }}
        </span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">
            {{ item.product.price }} &nbspруб
        </span>
                <span class="product_quantity">
            x {{ item.quantity }} шт.
        </span>
                <span class="product_cost">
            = {{ item.get_product_cost }} &nbspруб
        </span>
            </div>
        {% endfor %}
    </div>
    {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
    {#сведения о заказе (номер, дата создания и изменения, статус, количество товаров, общая стоимость)#}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {#Форма создания самого заказа, при работе с CBV, рендерим ее при помощи метода «.as_p()​»​#}
            {{ form.as_p }}
            <table class="table">
                {#Обязательно ​выводим служебную форму для набора форм элементов заказа:#}
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                {#Шаблон​ный тег «cycle​» ​позволяет для каждого из столбцов таблицы присвоить свой класс.#}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {#form​.hidden_fields - скрытые поля#}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {#Ошибки поля#}
                                {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
                                    {{ field }}
                                {% else %}
                                    {% if field.value %} {#вывод цены как текстового поля#}
                                        {#Для того, чтобы считать данные о ценах товаров, необходимо задать каждому #}
                                        {#значению свой идентификатор. Это могут быть атрибуты «class» или «id​»​. Допустим #}
                                        {#наши идентификаторы должны иметь вид - orderitems-<​номер​ элемента заказа>-price. #}
                                        {#Используем для их генерации ​счетчик​ внешнего (parentloop) цикла #}
                                        {#(по формам набора), начинающийся с нуля (counter0)#}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }}
                                        </span> руб
                                    {% endif %}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить
            </button>
            {#действия на странице с заказом (совершение покупки, удаление, возврат к списку заказов, возврат на главную страницу)#}
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}


{% block content %}
    <div class="h2 text-center head">
        Ваши заказы,
        {% if user.first_name %}
            {{ user.first_name|title }}
        {% else %}
            Пользователь
        {% endif %}
    </div>
    <table class="table orders_list">
        <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            {% if item.is_active %} {# показываем в списке только активные заказы #}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    {# Метод для корректного отображения атрибута модели с выбором из списка значений «get_<имя атрибута>_display()» #}
                    <td>
                        <a href="{% url 'ordersapp:order_read' item.pk %}">
                            посмотреть
                        </a>
                    </td>
                    <td>
                        {% if item.status == 'FM' %} {# действие доступно только на стадии формирования заказа #}
                            <a href="{% url 'ordersapp:order_update' item.pk %}">
                                редактировать
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:order_delete' item.pk %}">
                                удалить
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'mainapp:index' %}">
            на главную
        </a>
    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'ordersapp:order_create' %}">
            новый
        </a>
    </button>
{% endblock %}